version: '3'
services:
    payara-full:

        build:
          context: ..
          dockerfile: docker/Dockerfile
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara/appserver/bin/asadmin
            - start-domain
            - -v
        volumes:
            - data-payara:/opt/payara/appserver/glassfish/domains/production/autodeploy/
        depends_on:
            - db

    db:
        image: postgres:11.5
        ports:
          - "5432:5432"
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - data-pgdata:/var/lib/postgresql/data/pgdata
volumes:
  data-pgdata:
  data-payara:
