version: '3'
services:
    payara-full:

        build:
          context: ..
          dockerfile: docker/Dockerfile
          args:
            - http_proxy=$http_proxy
            - https_proxy=$https_proxy
            - HTTP_PROXY=$HTTP_PROXY
            - HTTPS_PROXY=$HTTPS_PROXY
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara/appserver/bin/asadmin
            - start-domain
            - -v
        volumes:
            - data-payara:/opt/payara/appserver/glassfish/domains/production/autodeploy/
        depends_on:
            - db

    db:
        image: postgres:11.5
        ports:
          - "5432:5432"
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - data-pgdata:/var/lib/postgresql/data/pgdata

    db1:
      image: couchdb:2.3.0
      ports:
        - "5984:5984"
      environment:
        NODENAME: couchdb-0.docker.com
        COUCHDB_PASSWORD: admin
        COUCHDB_USER: admin
      networks:
        network:
          aliases:
            - couchdb-0.docker.com
      volumes:
        - data-couchdb1:/opt/couchdb/data

    db2:
      image: couchdb:2.3.0
      ports:
        - "15984:5984"
      environment:
        NODENAME: couchdb-2.docker.com
        COUCHDB_PASSWORD: admin
        COUCHDB_USER: admin
      networks:
        network:
          aliases:
            - couchdb-2.docker.com
      volumes:
        - data-couchdb2:/opt/couchdb/data


    db3:
      image: couchdb:2.3.0
      ports:
        - "25984:5984"
      environment:
        NODENAME: couchdb-3.docker.com
        COUCHDB_PASSWORD: admin
        COUCHDB_USER: admin
      networks:
        network:
          aliases:
            - couchdb-3.docker.com
      volumes:
        - data-couchdb3:/opt/couchdb/data



networks:
  network:

volumes:
  data-pgdata:
  data-payara:
  data-couchdb1:
  data-couchdb2:
  data-couchdb3:
